try {
  console.log("hello nitin");
} catch (errorType1) {
  console.log("there is some error");
} finally {
  console.log(
    "this code will run no matter what happens in the try and catch blocks"
  );
}
